version: 2
jobs:
  build:
   docker:
      - image: mrmiss/doker:latest
   steps:
      - checkout
      - run: git clone https://github.com/akhilnarang/scripts buildenv && cd buildenv && bash setup/android_build_env.sh && cd ..
      - run: wget https://raw.githubusercontent.com/keselekpermen69/scripts/master/kernel.sh
      - run: bash kernel.sh
